echo 1 >> log
kdreams 1.BIN >> log
echo 2 >> log
kdreams 2.BIN >> log
echo 3 >> log
kdreams 3.BIN >> log
echo 4 >> log
kdreams 4.BIN >> log
echo 5 >> log
kdreams 5.BIN >> log
echo 6 >> log
kdreams 6.BIN >> log
echo 7 >> log
kdreams 7.BIN >> log
echo 8 >> log
kdreams 8.BIN >> log
echo 9 >> log
kdreams 9.BIN >> log
echo 10 >> log
kdreams 10.BIN >> log
echo 11 >> log
kdreams 11.BIN >> log
echo 12 >> log
kdreams 12.BIN >> log
echo 13 >> log
kdreams 13.BIN >> log
echo 14 >> log
kdreams 14.BIN >> log
echo 15 >> log
kdreams 15.BIN >> log
echo 16 >> log
kdreams 16.BIN >> log
